### ISSUE TITLE
Node version 

### ISSUE THREAD

**Issue by owengombas** [arkenthera/electron-vibrancy#23]
I can't launch my app...
I installed it with, npm install...  

![image](https://user-images.githubusercontent.com/17951357/37653736-26cc33ce-2c40-11e8-9a50-d4f1bb1d747a.png)

**Comment by 23phy** [comment]
Hello @OwenCalvin, this is because the npm module of ```electron-vibrancy```, that comes from npm, was compiled against a different version of Electron, to simply resolve this issue, you have three possibilities
1. Manually compile the npm module against the one you're using by:
  - opening a terminal/command prompt or any other terminal aplication in your root project folder (you can hold Shift and right click, choose  ```Open Command Prompt window here```) 
  - change your directory to electron-vibrancy module like so: ```cd npm_modules/electron-vibrancy```
  - take note of your electron version by: ```electron --version```
  - install node-gyp globally: ```npm i node-gyp -g``` (skip this if you already have it)
  - finally build the module by using this command: ```node-gyp rebuild --target=[YOUR-ELECTRON-VERSION] --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell``` and voilà, it should be working now.
    - example: ```node-gyp rebuild --target=1.8.4 --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell```
2. Using electron-rebuild to automatically compile it for you:
  - install electron-rebuild as a development dependency: ```npm i electron-rebuild --save-dev```
  - then run it like so: ```.\node_modules\.bin\electron-rebuild.cmd```. I assume this will search your package.json for dependencies that needs to be rebuild, and well.. rebuild them, for it to work you have to have ```electron-vibrancy``` as a dependency in your project, otherwise it won't be built.
3. Kindly ask the owner to update the npm module, and install it again.

**Comment by parkerduckworth** [comment]
@23phy Had this same issue.  Rebuilt the module with an updated electron version and it did the trick.  Thanks for the helpful comment.
